"""Conversions FHIR R4 v1.6.0 — mapping entre modèles internes GuinéeCare et ressources FHIR R4.

Référence : HL7 FHIR R4 (https://hl7.org/fhir/R4/).

Ressources supportées :
- `Patient` → `app.modules.patients.models.Patient`
- `Encounter` → `app.modules.admissions.models.Admission`
- `Observation` → `app.modules.clinical.models.PatientMeasurement` (constantes) +
  `app.modules.laboratory.models.LabResult` (résultats labo)
- `MedicationRequest` → `app.modules.clinical.models.ClinicalNote` (note_type=PRESCRIPTION)
- `DiagnosticReport` → `app.modules.imaging.models.ImagingResult`

Conventions FHIR respectées :
- IDs FHIR = IDs internes (UUIDs).
- `meta.lastUpdated` = `updated_at` ou `created_at` de l'entité interne.
- `identifier` : `patient_number`, `national_id` (avec system distincts).
- `subject` : référence Patient (relative URL `Patient/{id}`).
- `status` : mapping vers les codes FHIR (active/finished/preliminary/final/...).
- Codes LOINC pour les observations labo, SNOMED CT pour les constantes vitales.

Notes :
- Les ressources FHIR sont générées à la volée (pas de cache persistant en v1.6).
- Les tags `meta.tag` incluent `GUINEECARE` pour traçabilité.
"""
from datetime import date, datetime
from typing import Any

from app.modules.admissions.models import Admission
from app.modules.clinical.models import ClinicalNote, PatientMeasurement
from app.modules.imaging.models import ImagingResult
from app.modules.laboratory.models import LabResult
from app.modules.patients.models import Patient


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

GUINEECARE_SYSTEM = "https://guineecare.gn/fhir"
PATIENT_NUMBER_SYSTEM = "https://guineecare.gn/identifiers/patient-number"
NATIONAL_ID_SYSTEM = "https://guineecare.gn/identifiers/national-id"
ENCOUNTER_NUMBER_SYSTEM = "https://guineecare.gn/identifiers/encounter"
LOINC_SYSTEM = "http://loinc.org"
SNOMED_SYSTEM = "http://snomed.info/sct"

# Mapping constantes vitales → codes LOINC
VITAL_LOINC = {
    "HEART_RATE": ("8867-4", "Heart rate"),
    "BLOOD_PRESSURE_SYSTOLIC": ("8480-6", "Systolic blood pressure"),
    "BLOOD_PRESSURE_DIASTOLIC": ("8462-4", "Diastolic blood pressure"),
    "TEMPERATURE": ("8310-5", "Body temperature"),
    "RESPIRATORY_RATE": ("9279-1", "Respiratory rate"),
    "OXYGEN_SATURATION": ("59408-5", "Oxygen saturation in Arterial blood"),
    "WEIGHT": ("29463-7", "Body weight"),
    "HEIGHT": ("8302-2", "Body height"),
    "GLUCOSE": ("2339-0", "Glucose in Blood"),
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _iso(dt):
    """Convertit en ISO 8601 (format FHIR)."""
    if dt is None:
        return None
    if isinstance(dt, datetime):
        return dt.isoformat()
    if isinstance(dt, date):
        return dt.isoformat()
    return None


def _gender_fhir(internal):
    """Mapping genre interne (M/F/O) → FHIR (male/female/other/unknown)."""
    if not internal:
        return None
    mapping = {
        "M": "male",
        "F": "female",
        "O": "other",
        "U": "unknown",
    }
    return mapping.get(internal.upper(), "unknown")


def _meta(resource_type, id_, last_updated=None):
    """Construit le bloc `meta` standard."""
    return {
        "versionId": "1",
        "lastUpdated": _iso(last_updated) or _iso(datetime.utcnow()),
        "tag": [
            {
                "system": GUINEECARE_SYSTEM,
                "code": "GUINEECARE",
                "display": "Generated by GuinéeCare Hospital Suite",
            }
        ],
    }


def _reference(resource_type, id_):
    """Construit une référence FHIR (relative URL)."""
    return {"reference": f"{resource_type}/{id_}"}


def _identifier(system, value):
    return {"system": system, "value": value}


def _codeable_concept(system, code, display=None):
    cc = {"coding": [{"system": system, "code": code}]}
    if display:
        cc["coding"][0]["display"] = display
        cc["text"] = display
    return cc


# ---------------------------------------------------------------------------
# Patient → FHIR Patient
# ---------------------------------------------------------------------------

def patient_to_fhir(patient):
    """Convertit un Patient GuinéeCare en ressource FHIR Patient R4.

    Champs mappés :
    - `identifier` : patient_number (obligatoire) + national_id (si présent).
    - `name` : family + given (official use).
    - `gender` : male/female/other/unknown.
    - `birthDate` : YYYY-MM-DD.
    - `telecom` : phone (mobile).
    - `address` : text (concaténation).
    - `active` : true si status == ACTIVE.
    """
    identifiers = [_identifier(PATIENT_NUMBER_SYSTEM, patient.patient_number)]
    if patient.national_id:
        identifiers.append(_identifier(NATIONAL_ID_SYSTEM, patient.national_id))

    fhir = {
        "resourceType": "Patient",
        "id": patient.id,
        "meta": _meta("Patient", patient.id, patient.created_at),
        "identifier": identifiers,
        "name": [
            {
                "use": "official",
                "family": patient.last_name,
                "given": [patient.first_name],
            }
        ],
        "active": patient.status == "ACTIVE",
    }

    gender = _gender_fhir(patient.gender)
    if gender:
        fhir["gender"] = gender

    if patient.date_of_birth:
        fhir["birthDate"] = _iso(patient.date_of_birth)

    if patient.phone:
        fhir["telecom"] = [{"system": "phone", "value": patient.phone, "use": "mobile"}]

    if patient.address:
        fhir["address"] = [{"text": patient.address}]

    if patient.insurance_number:
        fhir.setdefault("identifier", []).append(
            _identifier(f"{GUINEECARE_SYSTEM}/insurance", patient.insurance_number)
        )

    # Contact d'urgence
    if patient.emergency_contact_name or patient.emergency_contact_phone:
        contact = {"relationship": [{"text": "Emergency contact"}]}
        if patient.emergency_contact_name:
            contact["name"] = {"text": patient.emergency_contact_name}
        if patient.emergency_contact_phone:
            contact["telecom"] = [{"system": "phone", "value": patient.emergency_contact_phone}]
        fhir["contact"] = [contact]

    return fhir


# ---------------------------------------------------------------------------
# Admission → FHIR Encounter
# ---------------------------------------------------------------------------

def admission_to_fhir(admission, patient=None):
    """Convertit une Admission en ressource FHIR Encounter R4.

    Statuts mappés (basés sur le modèle Admission réel) :
    - OPEN → in-progress (admission active)
    - CLOSED → finished (patient sorti)
    - CANCELLED → cancelled
    """
    status_map = {
        "OPEN": "in-progress",
        "CLOSED": "finished",
        "ACTIVE": "in-progress",
        "DISCHARGED": "finished",
        "SCHEDULED": "planned",
        "CANCELLED": "cancelled",
    }
    admission_status = getattr(admission, "status", "OPEN") or "OPEN"
    fhir_status = status_map.get(admission_status.upper(), "unknown")

    # Class mapping (AMBULATORY/EMERGENCY/INPATIENT/etc.)
    class_map = {
        "ROUTINE": ("AMB", "ambulatory"),
        "EMERGENCY": ("EMER", "emergency"),
        "URGENT": ("EMER", "emergency"),
        "SURGERY": ("SURG", "surgical"),
        "MATERNITY": ("MAT", "maternity"),
    }
    admission_type = getattr(admission, "admission_type", "ROUTINE") or "ROUTINE"
    class_code, class_display = class_map.get(admission_type, ("AMB", "ambulatory"))

    fhir = {
        "resourceType": "Encounter",
        "id": admission.id,
        "meta": _meta("Encounter", admission.id, getattr(admission, "admitted_at", None)),
        "status": fhir_status,
        "class": {
            "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
            "code": class_code,
            "display": class_display,
        },
        "subject": _reference("Patient", admission.patient_id),
    }

    if admission.facility_id:
        fhir["serviceProvider"] = {"reference": f"Organization/{admission.facility_id}"}

    admitted_at = getattr(admission, "admitted_at", None)
    closed_at = getattr(admission, "closed_at", None)
    if admitted_at:
        period = {"start": _iso(admitted_at)}
        if closed_at:
            period["end"] = _iso(closed_at)
        fhir["period"] = period

    return fhir


# ---------------------------------------------------------------------------
# PatientMeasurement (constantes) → FHIR Observation
# ---------------------------------------------------------------------------

def measurement_to_fhir(measurement, patient_id):
    """Convertit une constante vitale en ressource FHIR Observation R4.

    Le champ `measurement_type` est mappé vers un code LOINC standard.
    """
    m_type = getattr(measurement, "measurement_type", None) or "UNKNOWN"
    loinc = VITAL_LOINC.get(m_type)
    if not loinc:
        code, display = "0", m_type
    else:
        code, display = loinc

    # Value : essayer de parser en Quantity
    value = getattr(measurement, "value", None)
    unit = getattr(measurement, "unit", None) or ""
    try:
        numeric_value = float(str(value).split()[0])
        value_quantity = {"value": numeric_value, "unit": unit}
    except (ValueError, TypeError):
        value_quantity = {"valueString": str(value)} if value else None

    fhir = {
        "resourceType": "Observation",
        "id": measurement.id,
        "meta": _meta("Observation", measurement.id, getattr(measurement, "recorded_at", None)),
        "status": "final",
        "category": [
            {
                "coding": [{
                    "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                    "code": "vital-signs",
                    "display": "Vital Signs",
                }]
            }
        ],
        "code": _codeable_concept(LOINC_SYSTEM, code, display),
        "subject": _reference("Patient", patient_id),
    }

    measured_at = getattr(measurement, "measured_at", None) or getattr(measurement, "recorded_at", None)
    fhir["effectiveDateTime"] = _iso(measured_at)

    if value_quantity:
        fhir["valueQuantity"] = value_quantity

    return fhir


# ---------------------------------------------------------------------------
# LabResult → FHIR Observation (labo)
# ---------------------------------------------------------------------------

def lab_result_to_fhir(lab_result, patient_id):
    """Convertit un résultat de laboratoire en ressource FHIR Observation R4.

    Statuts mappés :
    - PENDING → preliminary
    - VALIDATED → final
    - CANCELLED → cancelled
    - DRAFT → preliminary

    Le modèle LabResult ne contient pas `unit` ni `reference_range` — ces
    informations seraient à chercher dans le LabTest parent (v1.7).
    """
    status = getattr(lab_result, "status", None) or "PENDING"
    status_map = {
        "PENDING": "preliminary",
        "VALIDATED": "final",
        "CANCELLED": "cancelled",
        "DRAFT": "preliminary",
    }
    fhir_status = status_map.get(status.upper(), "unknown")

    fhir = {
        "resourceType": "Observation",
        "id": lab_result.id,
        "meta": _meta("Observation", lab_result.id, getattr(lab_result, "entered_at", None)),
        "status": fhir_status,
        "category": [
            {
                "coding": [{
                    "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                    "code": "laboratory",
                    "display": "Laboratory",
                }]
            }
        ],
        "code": _codeable_concept(LOINC_SYSTEM, "0", "Laboratory result"),
        "subject": _reference("Patient", patient_id),
    }

    # Value
    result_value = getattr(lab_result, "result_value", None)
    if result_value:
        try:
            numeric_value = float(str(result_value).split()[0])
            fhir["valueQuantity"] = {"value": numeric_value}
        except (ValueError, TypeError):
            fhir["valueString"] = str(result_value)

    # Interpretation
    interpretation = getattr(lab_result, "interpretation", None)
    if interpretation:
        interp = interpretation.upper()
        if "CRITIQUE" in interp or "CRITICAL" in interp:
            fhir["interpretation"] = [{
                "coding": [{
                    "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                    "code": "HX",
                    "display": "Critical high",
                }]
            }]
        elif "HAUT" in interp or "HIGH" in interp:
            fhir["interpretation"] = [{
                "coding": [{
                    "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                    "code": "H",
                    "display": "High",
                }]
            }]
        elif "BAS" in interp or "LOW" in interp:
            fhir["interpretation"] = [{
                "coding": [{
                    "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                    "code": "L",
                    "display": "Low",
                }]
            }]

    # Effective date
    entered_at = getattr(lab_result, "entered_at", None)
    validated_at = getattr(lab_result, "validated_at", None)
    if validated_at:
        fhir["effectiveDateTime"] = _iso(validated_at)
    elif entered_at:
        fhir["effectiveDateTime"] = _iso(entered_at)

    return fhir


# ---------------------------------------------------------------------------
# ClinicalNote (PRESCRIPTION) → FHIR MedicationRequest
# ---------------------------------------------------------------------------

def prescription_to_fhir(note, patient_id):
    """Convertit une ClinicalNote (note_type=PRESCRIPTION) en FHIR MedicationRequest.

    Le champ `content` contient la prescription en texte libre. En v1.6 on ne
    parse pas le contenu — on le met dans `medicationCodeableConcept.text`.
    """
    note_status = getattr(note, "status", None) or "ACTIVE"
    status_map = {
        "ACTIVE": "active",
        "COMPLETED": "completed",
        "CANCELLED": "cancelled",
        "DRAFT": "draft",
    }
    fhir_status = status_map.get(note_status.upper(), "active")

    fhir = {
        "resourceType": "MedicationRequest",
        "id": note.id,
        "meta": _meta("MedicationRequest", note.id, note.created_at),
        "status": fhir_status,
        "intent": "order",
        "subject": _reference("Patient", patient_id),
        "authoredOn": _iso(note.created_at),
    }

    content = getattr(note, "content", None)
    if content:
        fhir["medicationCodeableConcept"] = {"text": content[:500]}

    author_id = getattr(note, "author_id", None)
    if author_id:
        fhir["requester"] = {"reference": f"Practitioner/{author_id}"}

    return fhir


# ---------------------------------------------------------------------------
# ImagingResult → FHIR DiagnosticReport
# ---------------------------------------------------------------------------

def imaging_result_to_fhir(result, patient_id):
    """Convertit un ImagingResult en ressource FHIR DiagnosticReport R4.

    Statuts mappés :
    - DRAFT → preliminary
    - VALIDATED → final
    - CANCELLED → cancelled
    """
    status = getattr(result, "status", None) or "VALIDATED"
    status_map = {
        "DRAFT": "preliminary",
        "VALIDATED": "final",
        "CANCELLED": "cancelled",
    }
    fhir_status = status_map.get(status.upper(), "final")

    fhir = {
        "resourceType": "DiagnosticReport",
        "id": result.id,
        "meta": _meta("DiagnosticReport", result.id, result.created_at),
        "status": fhir_status,
        "code": _codeable_concept(LOINC_SYSTEM, "18748-4", "Diagnostic imaging report"),
        "subject": _reference("Patient", patient_id),
    }

    # Conclusion
    conclusion_parts = []
    findings = getattr(result, "findings", None)
    if findings:
        conclusion_parts.append(f"Findings: {findings}")
    conclusion = getattr(result, "conclusion", None)
    if conclusion:
        conclusion_parts.append(f"Conclusion: {conclusion}")
    if conclusion_parts:
        fhir["conclusion"] = "\n".join(conclusion_parts)

    # Effective date
    reported_at = getattr(result, "reported_at", None)
    if reported_at:
        fhir["effectiveDateTime"] = _iso(reported_at)
    elif hasattr(result, "created_at"):
        fhir["effectiveDateTime"] = _iso(result.created_at)

    return fhir


# ---------------------------------------------------------------------------
# Bundle helpers
# ---------------------------------------------------------------------------

def bundle(resources, *, total=None, type_="searchset"):
    """Construit une Bundle FHIR R4 contenant les ressources."""
    return {
        "resourceType": "Bundle",
        "id": f"bundle-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
        "type": type_,
        "total": total if total is not None else len(resources),
        "entry": [
            {
                "fullUrl": f"{r['resourceType']}/{r['id']}",
                "resource": r,
            }
            for r in resources
        ],
    }


def operation_outcome(severity, code, diagnostics):
    """Construit une ressource OperationOutcome FHIR pour les erreurs."""
    return {
        "resourceType": "OperationOutcome",
        "issue": [
            {
                "severity": severity,
                "code": code,
                "diagnostics": diagnostics,
            }
        ],
    }
